- name: Create database
  mysql_db:
    name: "{{ phpmyadmin_database }}"
  register: database
  delegate_to: "{{ phpmyadmin_server }}"

- name: Create PHPMyAdmin control user
  mysql_user:
    name: "{{ phpmyadmin_user }}"
    host: "{{ phpmyadmin_client_ip }}"
    password: "{{ phpmyadmin_password }}"
    priv: "{{ phpmyadmin_database }}.*:ALL"
  delegate_to: "{{ phpmyadmin_server }}"

- name: Importing MySQL schema
  mysql_db:
    name: "{{ phpmyadmin_database }}"
    state: import
    target: /usr/share/dbconfig-common/data/phpmyadmin/install/mysql
    login_host: "{{ phpmyadmin_server_ip }}"
    login_user: "{{ phpmyadmin_user }}"
    login_password: "{{ phpmyadmin_password }}"
  when: database.changed
